Models/ErrorViewModel.cs
using System;

namespace TestBeehive.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Hive.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestBeehive.Models
{
    public class Hive
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public DateTime InitDate { get; set; }

        //Later Adding LocationId and OwnerId
    }
}

Models/Measurement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TestBeehive.Models
{
    public class Measurement
    {
        [Key]
        public int ID { get; set; }

        [Required]
        public DateTime DT { get; set; }

        [Required]
        public double Weight { get; set; }

        [Required]
        public double Current { get; set; }

        [Required]
        [ForeignKey("HiveID")]
        public int HiveID { get; set; }

        public Measurement()
        {
            DT = DateTime.Now;
        }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TestBeehive.Models;

namespace TestBeehive.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MeasurementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TestBeehive.Data;
using TestBeehive.Models;

namespace TestBeehive.Controllers
{
    public class MeasurementController :  Controller
    {
        private readonly AppDbContext _db;

        public MeasurementController(AppDbContext db)
        {
            _db = db;
        }

        //GET - Index View
        public IActionResult Index()
        {
            IEnumerable<Measurement> objects = _db.Measurements;

            return View(objects);
        }

        //GET - Create View
        public IActionResult Create()
        {
            return View();
        }

        //POST - Create Measurement
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Measurement obj)
        {
            _db.Measurements.Add(obj);
            _db.SaveChanges();

            return RedirectToAction("Index"); //Back to Index View
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Measurement/Create.cshtml
@model TestBeehive.Models.Measurement

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>

        <div class="form-group row">
            <h2 class="text-info pl-3">Add Measurement</h2>
        </div>

        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Weight"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Weight" class="form-control" />
                        <span asp-validation-for="Weight" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <label asp-for="Current"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Current" class="form-control" />
                        <span asp-validation-for="Current" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <label asp-for="HiveID"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="HiveID" class="form-control" />
                        <span asp-validation-for="HiveID" class="text-danger"></span>
                    </div>

                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fa-solid fa-right-from-bracket"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @*Keep this empty*@
            </div>
        </div>

    </div>
</form>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />}

}

Views/Measurement/Index.cshtml
@model IEnumerable<TestBeehive.Models.Measurement>

<div class="container p-3">
    <div class="row" pt-4>
        <div class="col-6">
            <h2 class="text-primary">Measurement List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Measurement" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> &nbsp; Create New Measurement
            </a>
        </div>
    </div>

    <br /><br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th> Measurement</th>
                    <th> Date and Time</th>
                    <th> Weight</th>
                    <th>Current</th>
                    <th>HiveID</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                <tr>
                    <td width="50%">@obj.ID</td>
                    <td class="text-center">@obj.DT</td>
                    <td class="text-center">@obj.Weight</td>
                    <td class="text-center">@obj.Current</td>
                    <td class="text-center">@obj.HiveID</td>
                </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Measurement exists.</p>
    }

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestBeehive</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestBeehive</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Measurement" asp-action="Index">Measurement</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TestBeehive - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>